Profile/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [

    url(r'^login/', 'Profile.views.login'),
    url(r'^logout/', 'Profile.views.logout'),
    url(r'^register/', 'Profile.views.register'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Url_Shortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shortener.views import open_short_url

import shortener

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('Profile.urls')),
    url(r'^', include('shortener.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shortener/urls.py
from django.conf.urls import patterns,  include, url
from django.conf.urls.static import static
from shortener import views
from django.conf import settings

urlpatterns = [
    url(r'^add_url/', views.add_site),
    url(r'^([a-z]{5})/$', views.open_short_url),
    url(r'^$', views.add_site),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Profile/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User)

	def __unicode__(self):
		return "%s" % (self.user)

shortener/models.py
from django.db import models
from django.contrib.auth.models import User
from Url_Shortener import settings
from Profile.models import Profile
#from django.contrib import auth


class LongURL(models.Model):
    name = models.CharField(max_length = 100)
    ads  = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class ShortURL(models.Model):
    name = models.CharField(max_length = 50)
    clicks = models.IntegerField(default=0)
    long_link = models.ForeignKey(LongURL)
    user = models.ForeignKey(User, default=0, null = True)
    created_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

Profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.core.files.base import ContentFile
from django.db.models import Q
from django.http import *
from Profile.models import Profile

class LoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(widget=forms.PasswordInput, required=True)

	def clean(self):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")

		if not username or not password:
			return self.cleaned_data

		user = authenticate(username=username,
							password=password)

		if user:
			self.user = user
		else:
			raise ValidationError("Error!")

		return self.cleaned_data   

class RegistrationForm(UserCreationForm):
	
	class Meta:
		model = User
		fields = ("first_name", "last_name", "username", "email", "password1", "password2")
	 
	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)

		if commit:
			user.save()
		
		return user		

shortener/forms.py
from django import forms

class AddSite(forms.Form):
	CHOICES = (
        ('Yes_Ads', 'Yes Advertiment'),
        ('Not_Ads', 'Not Advertiment'),

    )
	link = forms.URLField(initial='http://')
	advertiment=forms.ChoiceField(choices=CHOICES, required=True, label='Example')

'''
class ChoiceForDelete(forms.Form):
	choices = forms.ModelMultipleChoiceField(
		widget  = forms.CheckboxSelectMultiple)'''

Profile/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.core.exceptions import ValidationError
from django.http import *
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from Profile.models import Profile
from Profile.forms import LoginForm, RegistrationForm

# Create your views  here.
def login(request):
	if not request.user.is_authenticated():
		context = {}
		try:
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)

			if user is not None:
				auth_login(request, user)
				return HttpResponseRedirect("/")
			else:
				context['error'] = 'Non active user'
				
		except:
			context['error'] = ''
			
		populateContext(request, context)	
		return render(request, 'login.html', context)

	else:
		return HttpResponseRedirect("/index/")

def populateContext(request, context):
	context['authenticated'] = request.user.is_authenticated()

	if context['authenticated'] == True:
		context['username'] = request.user.username


def logout(request):
	auth_logout(request)
	return redirect('/')

def register(request): 
	if not request.user.is_authenticated():
		form = RegistrationForm()

		if request.method == "POST":
			form = RegistrationForm(request.POST)

			if  form.is_valid():
				form.save()       
				return render(request,"/index/",
								   locals())
			else:
				form = RegistrationForm()
				return render(request,"register.html",
								   locals())
		else:
			form = RegistrationForm()
			return render(request, "register.html",{'form':form})

	else:
		return HttpResponseRedirect("/index/")    

shortener/views.py
from django.shortcuts import render
from django.http import  Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context_processors import csrf
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.db.models import F
from shortener.forms import AddSite
from shortener.models import ShortURL, LongURL
import random, string
import datetime


def add_site(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        form = AddSite(request.POST)
        if form.is_valid():

            flag = True
            while flag:
                key = ''.join(random.choice(string.ascii_lowercase) for i in range(5))
                if not ShortURL.objects.filter(name = key).exists():
                    flag = False


            long_u = LongURL(name = request.POST['link'],ads = form.cleaned_data["advertiment"])
            long_u.save()
            if auth.get_user(request).id is not None:
                user = auth.get_user(request)
            else:
                user = None
            now = datetime.datetime.now()
            short_u = ShortURL(name = key, long_link = long_u , user =user, created_date=now)
            short_u.save()
            whole_short_u = request.META['HTTP_HOST'] +'/' + '%s' %(short_u)

            
            args['short_url'] = short_u
            args['whole_short_u'] = whole_short_u
            args['username'] = auth.get_user(request).username
            

            return render_to_response('show_short.html', args)

        if 'delete' in request.POST:
            for item in request.POST.getlist('choices'):
                short = ShortURL.objects.get(id=item)
                short.long_link.delete()
                short.delete()
            return HttpResponseRedirect('/')
        return render(request,'add_site.html',{'error':" "})


    else:
        args['form'] = AddSite()
        args['username'] = auth.get_user(request).username
        args['short_urls_list'] = ShortURL.objects.filter(user=auth.get_user(request).id)
        args['host'] = request.META['HTTP_HOST']
        return render(request,'add_site.html', args)

def open_short_url(request, key):
    
    if ShortURL.objects.filter(name = key).exists():

        long_url = ShortURL.objects.get(name = key).long_link
        number = ShortURL.objects.get(name = key)
        number.clicks = F('clicks') + 1
        number.save()

        if ShortURL.objects.get(name = key).long_link.ads == "Yes_Ads":
        	return render(request,'ads.html',{'url':long_url})
       	else:
			return HttpResponseRedirect(long_url)
    else:
        return render(request,'ads.html',{'wrong':"Error"})

Profile/templates/login.html
{% extends 'main.html' %}

{% block login %}
	<div class="row centered">
	<div class='col col-6'>
		<form action='/auth/login/' method='post' class="form">
			{% csrf_token %}
		<fieldset>
		<legend>Login data</legend>
		<div class="row centered">
			<div class="col col-6">
				<div class="form-item">
					<label for='username'>Username</label>
					<input type='text' name='username' id='username'>
				</div>	
			</div>
		</div>	
		<div class="row centered">
			<div class="col col-6">
				<div class="form-item">
					<label for='password'>Password</label>
					<input type='password' name='password' id='password'>
				</div>	
			</div>
		</div>
		</fieldset>
		<div class="row centered">
			<div class="form-item">
				<input class='button ' type='submit' value='Login'>
				<a class="button " href="/auth/register/">Register!</a>
			</div>
		</div>
		</form>
	</div>
	</div>
{% endblock %}

Profile/templates/register.html
{% extends 'main.html' %}

{% block login %}
<div class="row centered">
	<div class='col col-6'>
	<form action="/auth/register/" method="post" class="form">
		{% csrf_token %}
		<fieldset>
		<legend>Register</legend>
		<div class="row">
		    <div class="col col-6">
				<div class="form-item">
					<label for="id_username">Username</label>
					<input maxlength="30" name="username" type="text">
				</div>
			</div>	
		    <div class="col col-6">
				<div class="form-item">
					<label for="id_email">E-mail</label>
					<input maxlength="254" name="email" type="email">
				</div>
			</div>	
		</div>
	<div class="row">
	    <div class="col col-6">
			<div class="form-item">
				<label for="id_password1">Password</label>
				<input name="password1" type="password">
			</div>
		</div>	
	    <div class="col col-6">
			<div class="form-item">
				<label for="id_password2">Password</label>
				<input name="password2" type="password">
			</div>
		</div>
	</div>	
		</fieldset>
	<div class="row centered">
		<div class="form-item">
			<input class="button" type="submit" value="Register">
		</div>
	</div>
	
	</form>
	</div>
</div>
{% endblock %}

shortener/templates/add_site.html
{% extends 'main.html' %}
{% block main %}
{% load staticfiles %}
<div class="row centered">
    <div class="col col-6">
    	<form action='' method='post' class="form">
    	{% csrf_token %}
        <fieldset>
        <legend>Link Short</legend>
        {% if error %}
        <div class="alert error"><h3>Link Error!</h3></div>
        {% endif %}   
        <div class="row centered">
            <div class="col col-6">
                <div class="form-item">
                    <label for='id_link'>Link</label>
                    <input id="id_link" name="link" type="url" value="http://" required pattern="https?://.+">
                </div>
            </div>
        </div>
        <div class="row centered">
            <div class="col col-6">
                <div class="form-item">    
                    <label for='id_advertiment'>Advertisement</label>    
                	<select id="id_advertiment" name="advertiment">
                    <option value="Yes_Ads">Yes Please</option>
                    <option value="Not_Ads">Of Course No!</option>
                    </select>
                </div>
            </div>
        </div>	
        </fieldset>
    <div class="row centered">
        <div class="form-item">
        <input class='button ' type='submit' value='Submit'>
        </div>
    </div>    
    	</form>
    </div>
</div>

    {% if username %}

<div class="row centered">
    <div class="col col-10">
    <form class="form" action="" method="post">
        {% csrf_token %}
    <fieldset>
        <legend>Link Short</legend>    
        <table class="striped">
            <thead>
                <tr>
                    <th></th>
                    <th>URL Adress</th>
                    <th>Create Time</th>
                    <th>Shortener URL</th>
                    <th>Cycle</th>
                </tr>
            </thead>
            <tbody>
                {% for url in short_urls_list %}
                    <tr>
                        <td><input type="checkbox" name="choices" value="{{url.id}}"></td>
                        <td><a href="{{url.long_link}}/"> {{url.long_link}}</a></td>
                        <td>{{ url.created_date}}</td>
                        <td><a href="/{{url}}/"> {{ host }}/{{url}}/ </a></td>
                        <td>{{url.clicks}}</td>
                    </tr>
                {% endfor %}
            </tbody>
	    </table>
        <button type="submit" name="delete" class="button">Delete</button>
    </fieldset>
    </form>
    </div>
</div>
	{% endif %}
{% endblock %}

shortener/templates/ads.html
{% extends 'main.html' %}
{% block ads %}	

{% if wrong %}
<div class="row centered">
	<div class="col col-3 ">
		<fieldset>
		<legend>Link</legend>
		<h2>Upss!</h2>
		</fieldset>
	</div>
</div>
{% else %}
<div class="row centered">
	<div class="col col-3 ">
		<fieldset>
		<legend>Link</legend>
		<div class="row centered">
			<a class='button primary' href ='{{ url }}'>Link GO!!</a>
		</div>
		</fieldset>
	</div>
</div>	

{% endif %}

{% endblock %}

shortener/templates/show_short.html
{% extends 'main.html' %}
{% block main %}	
	

	<div class="row centered">
    <div class="col col-3 ">
    	<fieldset>
        <legend>Link</legend>
        <div class="row centered">
		<a href ='/{{ short_url }}/'>{{ whole_short_u }}</a>

		</div>
		</fieldset>
	</div>
</div>	

{% endblock %}

shortener/templates/wrong.html
<html>
<head>
 <title>URL Shortener</title>
</head>
<body>
	<h1>Opss..</h1>
	<img src="oops.png">
	
</body>
</html>

templates/main.html
{% load static %}
<!DOCTYPE html>
	<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel='stylesheet' type='text/css' href={% static 'css/kube.min.css' %}>
		<link rel='stylesheet' type='text/css' href={% static 'css/main.css' %}>

		<title>URL Short</title>
	</head>
	<body class="page-kube">
		<div class="show-on-small">
    		<div id="nav-toggle-box">
    			<div id="nav-toggle-brand">
    			<a href="/">Home Page</a>
    		</div>
            <a href="#" id="nav-toggle" class="toggleme" data-target="#header" data-component-toggleme-loaded="true"><i class="menu-icon"></i></a>
    	</div>
	</div>
	<div id="header" class="hide-on-small">
		<div id="header-brand">
			
			<a href="/">Home Page</a>
			
		</div>
		<nav id="header-nav" >
			<ul>
			{% if username %}
				<li><a href='/admin/'>Admin</a></li>
				<li><a href='/auth/logout/'>Log Out ({{ username }})</a></li>

			{% else %}
				<li><a href='/auth/login/'>Login</a></li>
				<li><a href='/auth/register/'>Register</a></li>

			{% endif %}
			</ul>
		</nav>
		</div>
	
	{% block main %}{% endblock %}
	{% block login %}{% endblock %}
	{% block ads %}{% endblock %}
	

	

	</body>
	</html>